apiVersion: v1
kind: Service
metadata:
  name: secret-letter-frontend
  namespace: secret-letter
  labels:
    app.kubernetes.io/name: secret-letter-frontend
    app.kubernetes.io/part-of: secret-letter
spec:
  type: ClusterIP
  selector:
    app.kubernetes.io/name: secret-letter-frontend
  ports:
    - name: http
      port: 80
      targetPort: http
